version: '3.8'

services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    restart: always

  user-service:
    build:
      context: ./userservice
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - MONGO_URI=mongodb://mongo:27017/userdb
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - user-service
    restart: always
